Replace pyenv with conda environment

diff --git a/bin/create_venv b/bin/create_venv
--- a/bin/create_venv
+++ b/bin/create_venv
@@ -1,36 +1,56 @@
 #!/bin/bash
 
-### Creates the Python virtual environment ###
+script_cleanup() {
+    popd > /dev/null
+    trap - INT TERM
+}
 
-echo "Creating venv..."
+trap script_cleanup INT TERM
 
-# cd to script
-cd "$(dirname "$0")/.."
+pushd . > /dev/null
 
-# Create venv
-python3 -m venv ctfs
-if [ $? -ne 0 ]; then
-    echo "Internal error! Could not create virtual environment." >&2
-    exit 1
+# cd to one level above the script's dir
+cd "$(dirname "${BASH_SOURCE[0]}")"/..
+
+### Creates the Python virtual environment and downloads the compiler ###
+
+# Parse venv name from environment.yml
+VENVNAME="$(head -n 1 environment.yml)"
+if [ $? -ne 0 ]; then 
+    echo "Could not parse the environment name from environment.yml." >&2
+    return 1
 fi
-# Activate venv
-source ./ctfs/bin/activate
+VENVNAME=${VENVNAME//"name: "/}
 
-echo "Installing required packages..."
+# Check if venv is already activated
+if [ "$CONDA_DEFAULT_ENV" != "$VENVNAME" ]; then
+    # Activate the conda base env
+    CONDA_DIR="$(conda info --base)"
+    source "$CONDA_DIR"/etc/profile.d/conda.sh
+    if [ $? -ne 0 ]; then
+        echo "'conda' command failed. Please ensure conda has been added to PATH and that 'conda init' has been run." >&2
+        return 1
+    fi
 
-# Install pip
-python3 -m pip install pip --upgrade
-if [ $? -ne 0 ]; then
-    echo "Internal error! Could not install pip." >&2
-    exit 1
+    # Check if venv exists
+    if [ ! -d "$CONDA_DIR/envs/$VENVNAME" ]; then 
+        # Create the environment from the file
+        conda env create --file=environment.yml -n "$VENVNAME"
+        if [ $? -ne 0 ]; then
+            echo "conda env create failed: could not create venv named '$VENVNAME'" >&2
+            return 1
+        fi
+    fi
+
+    # Source the environment
+    conda activate "$VENVNAME"
+    if [ $? -ne 0 ]; then
+        echo "conda activate failed: could not activate '$VENVNAME'" >&2
+        return 1
+    fi
 fi
-# Install requirements.txt
-pip install -r requirements.txt
-if [ $? -ne 0 ]; then
-    echo "Internal error! Could not install the required packages." >&2
-    exit 1
-fi
 
-echo "Done."
+script_cleanup
+unset script_cleanup
 
-exit 0
+return 0
diff --git a/bin/fourier_routine b/bin/fourier_routine
--- a/bin/fourier_routine
+++ b/bin/fourier_routine
@@ -106,11 +106,19 @@ if ($HELP); then
 fi
 
 # cd to script
-cd "$(dirname "$0")"
+cd "$(dirname -- "$0")" # bin
+
+# Create and activate venv
+echo "Activating venv..."
+source ./create_venv
+if [ $? -ne 0 ]; then
+    echo "Internal error! Could not activate the virtual environment." >&2
+    exit 1
+fi
+echo "Done."
 
 # Compile executable
-mkdir -p ../build
-cd ../build
+mkdir -p ../build && cd ../build
 if [ ! -f "ctfs" ]; then
     echo "Compiling executable..."
     gfortran -o ctfs ../src/functions.f95 ../src/fourier.f95 ../src/ctfs.f95 -O3
@@ -141,21 +149,6 @@ mkdir -p "$FUNCTION/data" "$FUNCTION/figures"
 rm -f "$FUNCTION/data/*.dat"
 mv -t "$FUNCTION/data" *.dat
 cd ..
-
-# Create and activate venv
-if [ ! -d "ctfs" ]; then
-    ./bin/create_venv
-    if [ $? -ne 0 ]; then
-        exit 1
-    fi
-fi
-echo "Activating venv..."
-source ctfs/bin/activate
-if [ $? -ne 0 ]; then
-    echo "Internal error! Could not activate the virtual environment." >&2
-    exit 1
-fi
-echo "Done."
 
 # Plot output of calculations
 cd bin
